rules:
  no-unused-vars:
    - error
    # Vars use a suffix _ instead of a prefix because of file-scope private vars
    - varsIgnorePattern: (^unused|_$)
      argsIgnorePattern: ^(unused|_)
#  camelcase:
    #- error
    #- properties: never
#      allow: [^vfunc_, ^on_]
  object-curly-spacing:
    - error
    - always
  prefer-arrow-callback: error
globals:
  global: readonly

env:
  es2021: true
